const auditLogs = [
    {
        date: "2025-01-01T21:54:34.087Z",
        admin_user: "Joy Grace",
        admin_role: "Admin",
        description: "Admin Logged In",
        actionType: "Login",
        affectedData: "NOne",
    },
    {
        date: "2025-01-01T21:54:34.087Z",
        admin_user: "Joy Grace",
        admin_role: "Content Manager",
        description: "User Logged In",
        actionType: "Signup",
        affectedData: "WA 1234",
    },
    {
        date: "2025-01-01T21:54:34.087Z",
        admin_user: "Joy Grace",
        admin_role: "Admin",
        description: "Admin Logged In",
        actionType: "Login",
        affectedData: "NOne",
    },
    {
        date: "2025-01-01T21:54:34.087Z",
        admin_user: "Joy Grace",
        admin_role: "Content Manager",
        description: "User Logged In",
        actionType: "Signup",
        affectedData: "WA 1234",
    },
    {
        date: "2025-01-01T21:54:34.087Z",
        admin_user: "Joy Grace",
        admin_role: "Admin",
        description: "Admin Logged In",
        actionType: "Login",
        affectedData: "NOne",
    },
    {
        date: "2025-01-01T21:54:34.087Z",
        admin_user: "Joy Grace",
        admin_role: "Content Manager",
        description: "User Logged In",
        actionType: "Signup",
        affectedData: "WA 1234",
    },
    {
        date: "2025-01-01T21:54:34.087Z",
        admin_user: "Joy Grace",
        admin_role: "Admin",
        description: "Admin Logged In",
        actionType: "Login",
        affectedData: "NOne",
    },
    {
        date: "2025-01-01T21:54:34.087Z",
        admin_user: "Joy Grace",
        admin_role: "Content Manager",
        description: "User Logged In",
        actionType: "Signup",
        affectedData: "WA 1234",
    },
];

export default auditLogs